import type { IndustryConfig } from "./types";

export const hospitality: IndustryConfig = {
  id: "hospitality",
  label: "Hospitality",
  emoji: "🏨",
  tagline: "Know where your hotel, restaurant or experience appears in AI recommendations.",
  audience: "guests and travelers",
  subcategories: [
    {
      id: "hotel",
      label: "Hotel",
      group: "lodging",
      noun: "hotel",
      plural: "hotels",
      services: ["Boutique hotel", "Beachfront hotel", "Luxury hotel", "Business hotel"],
      specialties: ["Romantic getaways", "Rooftop bar", "Spa", "Family stays", "On-site restaurant"],
      target_customer: "Leisure travelers and couples",
      base: { luxury: 0.45, boutique: 0.45, romantic: 0.4, family: 0.4, business: 0.35, value: 0.4 },
    },
    {
      id: "resort",
      label: "Resort",
      group: "lodging",
      noun: "resort",
      plural: "resorts",
      services: ["Beach resort", "All-inclusive resort", "Golf resort", "Spa resort"],
      specialties: ["Family vacations", "Honeymoons", "Spa", "Golf", "Weddings"],
      target_customer: "Vacationing families and couples",
      base: { beachfront: 0.55, family: 0.5, wellness: 0.5, luxury: 0.45 },
    },
    {
      id: "vacation-rental",
      label: "Vacation rental",
      group: "lodging",
      noun: "vacation rental",
      plural: "vacation rentals",
      services: ["Beachfront villas", "Condo rentals", "Group houses"],
      specialties: ["Large groups", "Remote work", "Surf trips"],
      target_customer: "Groups and families",
      base: { value: 0.5, family: 0.5, local: 0.45 },
    },
    {
      id: "restaurant",
      label: "Restaurant",
      group: "dining",
      noun: "restaurant",
      plural: "restaurants",
      services: ["Puerto Rican cuisine", "Seafood", "Fine dining", "Brunch"],
      specialties: ["Date night", "Ocean views", "Private events", "Mofongo"],
      target_customer: "Locals and visitors",
      base: { dining: 0.6, local: 0.5, romantic: 0.4 },
    },
    {
      id: "bar",
      label: "Bar",
      group: "dining",
      noun: "bar",
      plural: "bars",
      services: ["Cocktail bar", "Rooftop bar", "Rum bar"],
      specialties: ["Live music", "Sunset drinks", "Rum tasting"],
      target_customer: "Locals and visitors",
      base: { nightlife: 0.6, local: 0.45 },
    },
    {
      id: "experience",
      label: "Tourism experience",
      group: "experience",
      noun: "tour company",
      plural: "tours",
      services: ["Bioluminescent bay tours", "Rainforest tours", "Snorkeling", "Food tours"],
      specialties: ["Families", "Private groups", "Cruise passengers"],
      target_customer: "Visitors and cruise passengers",
      base: { local: 0.55, family: 0.45 },
    },
  ],
  categories: [
    { id: "best-of", label: "Best-of lists" },
    { id: "romance", label: "Romance & occasions" },
    { id: "family", label: "Families" },
    { id: "luxury", label: "Luxury" },
    { id: "value", label: "Value" },
    { id: "location", label: "Location" },
    { id: "experiences", label: "Experiences" },
    { id: "business", label: "Business" },
  ],
  attrCategory: { romantic: "romance", family: "family", luxury: "luxury", value: "value", business: "business", walkability: "location", beachfront: "location", wellness: "experiences", nightlife: "experiences", dining: "experiences" },
  attributes: [
    { id: "luxury", label: "Luxury", rationale: "Luxury service and design", prose: "polished, luxury-level service", diagnosis: "luxury positioning", action: "Show the luxury details AI can quote: room categories, service standards, design credits and recent luxury-travel press.", keywords: ["luxury", "upscale", "five-star", "high-end", "premium"] },
    { id: "romantic", label: "Romantic", rationale: "Romantic positioning", prose: "a romantic, adults-oriented atmosphere", diagnosis: "romantic-stay positioning", action: "Publish a couples page (anniversary and honeymoon packages, best rooms for views, dinner pairings) and ask couples to mention the occasion in reviews.", keywords: ["romantic", "couple", "couples", "anniversary", "honeymoon", "date"] },
    { id: "boutique", label: "Boutique", rationale: "Boutique atmosphere", prose: "an intimate boutique feel", diagnosis: "boutique positioning", action: "Describe what makes the property boutique: room count, design story, personal service.", keywords: ["boutique", "intimate", "small", "design"] },
    { id: "beachfront", label: "Beachfront", rationale: "Beachfront setting", prose: "direct beach access and ocean views", diagnosis: "beachfront positioning", action: "Make beach access and ocean views explicit on your site and listings, with walking distances and photos AI can cite.", keywords: ["beach", "beachfront", "ocean", "oceanfront", "sea"] },
    { id: "family", label: "Family", rationale: "Family-friendly amenities", prose: "family-friendly rooms and amenities", diagnosis: "family-travel positioning", action: "State your family policy clearly: room configurations, kids' amenities and nearby activities, or position the property as adults-focused.", keywords: ["family", "kids", "children", "toddler"] },
    { id: "business", label: "Business travel", rationale: "Business-travel convenience", prose: "convenient business-travel amenities", diagnosis: "business-travel positioning", action: "Add a business-travel page: workspaces, Wi-Fi speeds, meeting rooms and distance to the Convention Center.", keywords: ["business", "work", "conference", "meeting", "convention"] },
    { id: "value", label: "Value", rationale: "Good value for the price", prose: "solid value for the price", diagnosis: "value story", action: "Publish rate ranges and what is included (breakfast, parking, fees) so AI can explain your value.", keywords: ["budget", "cheap", "affordable", "value", "deal", "price"] },
    { id: "dining", label: "Dining", rationale: "Well-regarded dining", prose: "a well-regarded restaurant", diagnosis: "dining reputation", action: "Give the restaurant its own page with menu, chef and hours, and get it listed in local dining guides.", keywords: ["restaurant", "dining", "food", "dinner", "brunch", "eat"] },
    { id: "walkability", label: "Walkable", rationale: "Walkable location", prose: "a walkable location close to restaurants and nightlife", diagnosis: "location and walkability story", action: "Publish a neighborhood guide from your front door: walking times to the beach, Old San Juan, restaurants and the airport.", keywords: ["walk", "walkable", "walking", "near", "close to"] },
    { id: "wellness", label: "Wellness", rationale: "Spa and wellness facilities", prose: "spa and wellness facilities", diagnosis: "wellness offering", action: "Describe the spa, pool and wellness programming in detail and list them on wellness-travel sites.", keywords: ["spa", "wellness", "yoga", "retreat", "pool", "relax"] },
    { id: "nightlife", label: "Rooftop & nightlife", rationale: "Rooftop and nightlife scene", prose: "a lively rooftop and bar scene", diagnosis: "rooftop and nightlife presence", action: "Promote the rooftop and bar as their own destinations: hours, events and listings on nightlife guides.", keywords: ["rooftop", "bar", "nightlife", "drinks", "party", "cocktail"] },
    { id: "local", label: "Local character", rationale: "Authentic local character", prose: "authentic Puerto Rican character", diagnosis: "local authenticity", action: "Tell the local story: Puerto Rican design, partners, food and culture, and get featured by the tourism board.", keywords: ["authentic", "local", "puerto rican", "culture"] },
  ],
  vars: {
    property_type: [
      { value: "boutique hotels", attrs: ["boutique"] },
      { value: "beachfront hotels", attrs: ["beachfront"] },
      { value: "luxury hotels", attrs: ["luxury"] },
      { value: "small hotels", attrs: ["boutique"] },
      { value: "family-friendly hotels", attrs: ["family"], persona: "Families" },
      { value: "hotels with a spa", attrs: ["wellness"] },
    ],
    occasion: [
      { value: "an anniversary", attrs: ["romantic"], persona: "Couples" },
      { value: "a honeymoon", attrs: ["romantic", "luxury"], persona: "Honeymooners" },
      { value: "a family vacation", attrs: ["family"], persona: "Families" },
      { value: "a business trip", attrs: ["business"], persona: "Business travelers" },
      { value: "a girls' weekend", attrs: ["nightlife", "dining"], persona: "Friend groups" },
      { value: "a wellness getaway", attrs: ["wellness"], persona: "Wellness travelers" },
      { value: "a long weekend", attrs: [], persona: "Leisure travelers" },
    ],
    traveler_type: [
      { value: "couples", attrs: ["romantic"], persona: "Couples" },
      { value: "families with young kids", attrs: ["family"], persona: "Families" },
      { value: "business travelers", attrs: ["business"], persona: "Business travelers" },
      { value: "first-time visitors", attrs: ["walkability", "local"], persona: "First-time visitors" },
      { value: "travelers on a budget", attrs: ["value"], persona: "Budget travelers" },
      { value: "solo travelers", attrs: ["walkability"], persona: "Solo travelers" },
    ],
    experience: [
      { value: "rooftop bars", attrs: ["nightlife"] },
      { value: "hotel restaurants for date night", attrs: ["dining", "romantic"], persona: "Couples" },
      { value: "hotel spas", attrs: ["wellness"] },
      { value: "hotel pools with an ocean view", attrs: ["beachfront", "wellness"] },
      { value: "hotel brunch spots", attrs: ["dining"] },
    ],
    amenity: [
      { value: "an ocean view", attrs: ["beachfront"] },
      { value: "a spa", attrs: ["wellness"] },
      { value: "a rooftop pool", attrs: ["nightlife", "wellness"] },
      { value: "free parking", attrs: ["value"] },
      { value: "a kids' club", attrs: ["family"], persona: "Families" },
      { value: "a great restaurant", attrs: ["dining"] },
    ],
    landmark: [
      { value: "Condado Beach", attrs: ["beachfront"] },
      { value: "Old San Juan", attrs: ["walkability", "local"] },
      { value: "the Convention Center", attrs: ["business"], persona: "Business travelers" },
      { value: "Ashford Avenue", attrs: ["walkability", "dining"] },
    ],
    price: [
      { value: "$200", attrs: ["value"], persona: "Budget travelers" },
      { value: "$350", attrs: [] },
      { value: "$500", attrs: ["luxury"] },
    ],
    cuisine: [
      { value: "Puerto Rican", attrs: ["local"] },
      { value: "seafood", attrs: ["beachfront"] },
      { value: "fine dining", attrs: ["luxury"] },
      { value: "brunch", attrs: ["dining"] },
      { value: "Latin fusion", attrs: ["dining"] },
    ],
    dining_occasion: [
      { value: "date night", attrs: ["romantic"], persona: "Couples" },
      { value: "a birthday dinner", attrs: ["romantic"] },
      { value: "a family dinner", attrs: ["family"], persona: "Families" },
      { value: "a business lunch", attrs: ["business"], persona: "Professionals" },
      { value: "a group celebration", attrs: ["nightlife"], persona: "Friend groups" },
    ],
    dining_style: [
      { value: "ocean views", attrs: ["beachfront"] },
      { value: "a lively atmosphere", attrs: ["nightlife"] },
      { value: "local flavors", attrs: ["local"] },
      { value: "a quiet romantic dinner", attrs: ["romantic"], persona: "Couples" },
      { value: "good value", attrs: ["value"] },
    ],
    tour_type: [
      { value: "bioluminescent bay tours", attrs: ["local"] },
      { value: "rainforest tours", attrs: ["family"] },
      { value: "snorkeling trips", attrs: ["beachfront"] },
      { value: "food tours", attrs: ["dining", "local"] },
      { value: "private boat charters", attrs: ["luxury"] },
    ],
  },
  templates: [
    // Lodging
    { id: "h-best-type-occasion", text: "Best {property_type} in {location} for {occasion}", intent: "best-of", category: "romance", funnel: "consideration", persona: "Leisure travelers", groups: ["lodging"] },
    { id: "h-stay-traveler", text: "Where should I stay in {location} for {traveler_type}?", intent: "discovery", category: "location", funnel: "awareness", persona: "Leisure travelers", groups: ["lodging"] },
    { id: "h-best-experience", text: "Best {experience} in {location}", intent: "best-of", category: "experiences", funnel: "consideration", persona: "Leisure travelers", groups: ["lodging"], scope: "local" },
    { id: "h-near-landmark", text: "Best {property_type} near {landmark} for {occasion}", intent: "local", category: "location", funnel: "consideration", persona: "Leisure travelers", groups: ["lodging"] },
    { id: "h-compare", text: "Which {property_type} in {location} are actually worth the price?", intent: "comparison", category: "luxury", funnel: "consideration", persona: "Leisure travelers", groups: ["lodging"], scope: "local" },
    { id: "h-book-amenity", text: "Book a hotel in {location} with {amenity}", intent: "transactional", category: "experiences", funnel: "decision", persona: "Leisure travelers", groups: ["lodging"], scope: "local" },
    { id: "h-high-occasion", text: "I'm visiting {location} for {occasion}. Which hotel should I book?", intent: "high-intent", category: "romance", funnel: "decision", persona: "Leisure travelers", groups: ["lodging"], scope: "local" },
    { id: "h-problem-amenity", text: "Where can I stay in {location} that has {amenity} and works for {traveler_type}?", intent: "problem", category: "family", funnel: "consideration", persona: "Leisure travelers", groups: ["lodging"] },
    { id: "h-walk-landmark", text: "Hotels within walking distance of {landmark}", intent: "local", category: "location", funnel: "consideration", persona: "Leisure travelers", groups: ["lodging"], attrs: ["walkability"] },
    { id: "h-value-price", text: "Best {property_type} in {location} under {price} a night", intent: "comparison", category: "value", funnel: "consideration", persona: "Leisure travelers", groups: ["lodging"], scope: "local" },
    { id: "h-business", text: "Best hotel in {location} for business travelers near {landmark}", intent: "high-intent", category: "business", funnel: "decision", persona: "Business travelers", groups: ["lodging"], attrs: ["business"], scope: "local" },
    // Dining
    { id: "d-best-cuisine", text: "Best {cuisine} restaurants in {location}", intent: "best-of", category: "best-of", funnel: "consideration", persona: "Diners", groups: ["dining"] },
    { id: "d-best-occasion", text: "Best restaurant in {location} for {dining_occasion}", intent: "best-of", category: "romance", funnel: "consideration", persona: "Diners", groups: ["dining"] },
    { id: "d-where-style", text: "Where should I eat in {location} if I want {dining_style}?", intent: "discovery", category: "experiences", funnel: "awareness", persona: "Diners", groups: ["dining"] },
    { id: "d-book", text: "Reserve a table in {location} for {dining_occasion}", intent: "transactional", category: "romance", funnel: "decision", persona: "Diners", groups: ["dining"], scope: "local" },
    { id: "d-high", text: "Which restaurant in {location} would you pick for {dining_occasion}?", intent: "high-intent", category: "best-of", funnel: "decision", persona: "Diners", groups: ["dining"], scope: "local" },
    { id: "d-compare", text: "{cuisine} restaurants in {location}: which one is best?", intent: "comparison", category: "best-of", funnel: "consideration", persona: "Diners", groups: ["dining"] },
    { id: "d-near", text: "Good restaurants near {landmark}", intent: "local", category: "location", funnel: "consideration", persona: "Visitors", groups: ["dining"] },
    // Experiences
    { id: "e-best", text: "Best {tour_type} in {location}", intent: "best-of", category: "experiences", funnel: "consideration", persona: "Visitors", groups: ["experience"] },
    { id: "e-traveler", text: "Things to do in {location} for {traveler_type}", intent: "discovery", category: "family", funnel: "awareness", persona: "Visitors", groups: ["experience"] },
    { id: "e-book", text: "Book {tour_type} near {location}", intent: "transactional", category: "experiences", funnel: "decision", persona: "Visitors", groups: ["experience"], scope: "local" },
    { id: "e-high", text: "Which {tour_type} would you recommend in {location} for {traveler_type}?", intent: "high-intent", category: "best-of", funnel: "decision", persona: "Visitors", groups: ["experience"] },
    { id: "e-compare", text: "{tour_type} in {location}: which company is best?", intent: "comparison", category: "best-of", funnel: "consideration", persona: "Visitors", groups: ["experience"] },
  ],
  marketNames: {
    lodging: ["La Ventana Suites", "Brisa Ocean House", "Palma Real Inn", "Hotel Almendro", "Costa Azul Residences"],
    dining: ["Fogón de Mar", "Cocina Almendro", "La Terraza Azul", "Pilón Kitchen", "Sal y Humo"],
    experience: ["Isla Luminosa Tours", "Yunque Trail Co.", "Bahía Kayak Adventures", "Sabor Food Walks"],
  },
  missingInfo: [
    "Room or menu details AI can quote",
    "Rate ranges and what is included",
    "Who the stay is best for (couples, families, business)",
    "Walking distances to key landmarks",
    "Editorial coverage from the last 12 months",
    "Event and celebration packages",
  ],
  askExamples: [
    "Would you recommend {name} for an anniversary?",
    "Is {name} good for families?",
    "What is {name} known for?",
    "Should I stay at {name} or {competitor}?",
  ],
};
