import type { IndustryConfig } from "../types";

export const hospitality: IndustryConfig = {
  id: "hospitality",
  label: "Hospitality",
  emoji: "🏨",
  tagline: "Know where your hotel, restaurant or experience appears in AI recommendations.",
  audience: "guests and travelers",
  categories: [
    {
      id: "hotel",
      label: "Hotel",
      noun: "hotel",
      plural: "hotels",
      services: ["Boutique hotel", "Beachfront hotel", "Business hotel", "Luxury hotel"],
      templateGroup: "lodging",
      focuses: ["couples", "a honeymoon", "families", "a business trip", "a girls' trip", "a long weekend"],
    },
    {
      id: "resort",
      label: "Resort",
      noun: "resort",
      plural: "resorts",
      services: ["All-inclusive resort", "Beach resort", "Golf resort", "Spa resort"],
      templateGroup: "lodging",
      focuses: ["couples", "a honeymoon", "families", "a golf trip", "a wellness retreat", "a destination wedding"],
    },
    {
      id: "vacation-rental",
      label: "Vacation rental",
      noun: "vacation rental",
      plural: "vacation rentals",
      services: ["Beachfront villas", "Condo rentals", "Group houses", "Surf rentals"],
      templateGroup: "lodging",
      focuses: ["large groups", "families", "surfers", "remote work", "couples", "a bachelorette"],
    },
    {
      id: "restaurant",
      label: "Restaurant",
      noun: "restaurant",
      plural: "restaurants",
      services: ["Puerto Rican cuisine", "Seafood", "Fine dining", "Brunch"],
      templateGroup: "dining",
      focuses: ["date night", "a birthday dinner", "mofongo", "seafood", "brunch", "a business dinner"],
    },
    {
      id: "bar",
      label: "Bar",
      noun: "bar",
      plural: "bars",
      services: ["Cocktail bar", "Rooftop bar", "Rum bar", "Live music"],
      templateGroup: "dining",
      focuses: ["cocktails", "live music", "a first date", "rum tasting", "sunset drinks", "a bachelor party"],
    },
    {
      id: "experience",
      label: "Tourism experience",
      noun: "tour",
      plural: "tours and experiences",
      services: ["Bioluminescent bay tours", "Rainforest tours", "Snorkeling", "Food tours"],
      templateGroup: "experience",
      focuses: ["families", "couples", "a cruise stopover", "adventure", "a rainy day", "first-time visitors"],
    },
  ],
  topics: [
    {
      id: "best-of",
      label: "Best of",
      phrase: "“best in town” questions",
      keywords: ["best", "top", "recommend", "where should i", "favorite", "must"],
      opportunity: {
        title: "Win more “best {service} in {city}” recommendations",
        why: "AI builds its “best of” lists from editorial roundups and review volume. Competitors appear in more of the lists it reads.",
        action: "Pitch travel editors and local guides for roundup inclusion and keep your profiles on TripAdvisor, Google and Yelp complete and current.",
      },
      winSignals: ["Inclusion in travel roundups", "High review volume", "Editorial awards"],
    },
    {
      id: "romance",
      label: "Date night & romance",
      phrase: "romantic experiences",
      keywords: ["romantic", "couple", "couples", "date", "honeymoon", "anniversary", "proposal"],
      opportunity: {
        title: "Become AI's answer for romantic stays in {city}",
        why: "AI recommends you for luxury, but you have low visibility for romantic experiences — one of the most-asked categories.",
        action: "Create a couples page (packages, best rooms for views, dinner pairings, proposal planning) and encourage couples to mention it in reviews.",
      },
      winSignals: ["Dedicated couples and honeymoon packages", "Reviews mentioning romance", "Sunset and view content"],
    },
    {
      id: "family",
      label: "Family trips",
      phrase: "family travel",
      keywords: ["family", "kids", "children", "kid-friendly", "family-friendly", "toddler"],
      opportunity: {
        title: "Clarify whether you're right for families",
        why: "AI isn't sure if you welcome families, so it plays it safe and recommends competitors that say so explicitly.",
        action: "State your family policy clearly: room configurations, kids' amenities, nearby activities — or position yourself explicitly as adults-focused.",
      },
      winSignals: ["Clear family amenities", "Family reviews", "Kids' activity content"],
    },
    {
      id: "luxury",
      label: "Luxury",
      phrase: "luxury",
      keywords: ["luxury", "upscale", "five-star", "5-star", "high-end", "exclusive", "boutique"],
      opportunity: {
        title: "Protect your luxury position",
        why: "You're strong here today, but a competitor's recent press is closing the gap on luxury queries.",
        action: "Refresh luxury-related content, pursue one premium publication feature this quarter and highlight design, service and amenities.",
      },
      winSignals: ["Luxury publication features", "Design and amenity detail", "Premium pricing signals"],
    },
    {
      id: "budget",
      label: "Value & budget",
      phrase: "value-focused questions",
      keywords: ["cheap", "budget", "affordable", "value", "deal", "price", "cost"],
      opportunity: {
        title: "Own a clear value story",
        why: "Value questions go to competitors that publish rates, packages and inclusions. AI has no price context for you.",
        action: "Publish rate ranges and what's included (breakfast, parking, resort fees) so AI can explain your value.",
      },
      winSignals: ["Published rate ranges", "Clear inclusions", "Value mentions in reviews"],
    },
    {
      id: "location",
      label: "Location",
      phrase: "location-based questions",
      keywords: ["near", "beachfront", "walkable", "airport", "old san juan", "condado", "close to", "where to stay"],
      opportunity: {
        title: "Make your location advantages explicit",
        why: "When guests ask where to stay, AI explains neighborhoods. It doesn't connect your property to what's walkable nearby.",
        action: "Create a neighborhood guide from your property's front door: walking times to beaches, restaurants, Old San Juan and the airport.",
      },
      winSignals: ["Neighborhood guides", "Walking-distance details", "Strong map listings"],
    },
    {
      id: "experiences",
      label: "Experiences",
      phrase: "experiences",
      keywords: ["experience", "things to do", "activities", "tour", "rooftop", "spa", "pool", "dining"],
      opportunity: {
        title: "Turn your on-site experiences into recommendations",
        why: "AI recommends places for what guests can do there. It knows little about your rooftop, dining or spa.",
        action: "Give each experience its own page with photos, hours and booking, and get them listed on local event and dining guides.",
      },
      winSignals: ["Dedicated pages for each experience", "Listings in event guides", "Social mentions of signature experiences"],
    },
    {
      id: "occasions",
      label: "Special occasions",
      phrase: "special occasions",
      keywords: ["birthday", "wedding", "bachelorette", "celebration", "event", "anniversary", "group"],
      opportunity: {
        title: "Get recommended for celebrations and events",
        why: "Occasion-based questions are high-value and AI recommends venues that clearly host them. You're rarely included.",
        action: "Publish event and celebration offerings with capacity, packages and past examples.",
      },
      winSignals: ["Event packages", "Celebration reviews", "Group booking options"],
    },
    {
      id: "tourist",
      label: "Visitor intent",
      phrase: "first-time visitor questions",
      keywords: ["visit", "first time", "trip", "vacation", "tourist", "weekend", "itinerary", "cruise"],
      opportunity: {
        title: "Appear in AI-built itineraries for {city}",
        why: "Visitors ask AI to plan whole trips. Businesses that publish itinerary-friendly content get added to those plans.",
        action: "Write a “48 hours in {city}” guide featuring your property and partners, and get included in tourism board listings.",
      },
      winSignals: ["Itinerary content", "Tourism board listings", "Travel blog mentions"],
    },
  ],
  templates: {
    lodging: [
      { topic: "romance", intent: "discovery", text: "Best {plural} in {city} for couples" },
      { topic: "luxury", intent: "high-intent", text: "Where should I stay in {city} for a luxury vacation?" },
      { topic: "location", intent: "local", text: "Best beachfront {plural} near {city}" },
      { topic: "romance", intent: "high-intent", text: "Best {plural} in {region} for a honeymoon" },
      { topic: "best-of", intent: "comparison", text: "Best boutique {plural} in {city}" },
      { topic: "family", intent: "discovery", text: "Family-friendly {plural} in {city}" },
      { topic: "budget", intent: "comparison", text: "Best value {plural} in {city} under $250 a night" },
      { topic: "experiences", intent: "discovery", text: "{plural} in {city} with the best rooftop or pool" },
      { topic: "occasions", intent: "problem", text: "Where should I stay in {region} for {focus}?" },
      { topic: "tourist", intent: "problem", text: "First time in {region} — is {city} a good place to stay?" },
      { topic: "tourist", intent: "discovery", text: "Best area to stay in {region} for {focus}" },
      { topic: "location", intent: "local", text: "Walkable {plural} near Old San Juan and the beach" },
      { topic: "best-of", intent: "transactional", text: "Book a {noun} in {city} for {focus}" },
      { topic: "luxury", intent: "comparison", text: "Most luxurious {plural} in {region}" },
      { topic: "romance", intent: "comparison", text: "Romantic {noun} in {city} with ocean views" },
    ],
    dining: [
      { topic: "best-of", intent: "discovery", text: "Best {plural} in {city}" },
      { topic: "romance", intent: "high-intent", text: "Best {plural} in {city} for date night" },
      { topic: "luxury", intent: "comparison", text: "Best fine dining in {region}" },
      { topic: "location", intent: "local", text: "Where to eat near {city} tonight" },
      { topic: "experiences", intent: "discovery", text: "{plural} in {city} with live music or a view" },
      { topic: "budget", intent: "comparison", text: "Good affordable {plural} in {city}" },
      { topic: "occasions", intent: "high-intent", text: "Best {noun} in {city} for {focus}" },
      { topic: "family", intent: "discovery", text: "Family-friendly {plural} in {city}" },
      { topic: "tourist", intent: "problem", text: "Where do locals eat in {region}?" },
      { topic: "best-of", intent: "transactional", text: "Reserve a table at a top {noun} in {city}" },
      { topic: "romance", intent: "comparison", text: "Most romantic {plural} in {region}" },
      { topic: "occasions", intent: "problem", text: "Where can I host a private dinner for 20 in {city}?" },
    ],
    experience: [
      { topic: "best-of", intent: "discovery", text: "Best {plural} in {region}" },
      { topic: "family", intent: "discovery", text: "Best things to do in {region} with kids" },
      { topic: "romance", intent: "high-intent", text: "Romantic things to do in {city} for couples" },
      { topic: "tourist", intent: "problem", text: "What should I do in {region} on {focus}?" },
      { topic: "experiences", intent: "comparison", text: "Best bioluminescent bay tour in {region}" },
      { topic: "luxury", intent: "discovery", text: "Private luxury tours in {region}" },
      { topic: "budget", intent: "comparison", text: "Affordable tours near {city}" },
      { topic: "location", intent: "local", text: "Tours that pick up from {city}" },
      { topic: "occasions", intent: "high-intent", text: "Group activities in {region} for {focus}" },
      { topic: "best-of", intent: "transactional", text: "Book a tour in {region} for {focus}" },
    ],
  },
  strengths: [
    "Strong local presence in {city}",
    "Clear identity and offering",
    "Positive guest reviews",
    "Relevant website content",
    "Coverage in travel publications",
    "Distinctive design and atmosphere",
  ],
  missingInfo: [
    "Room or menu details AI can quote",
    "Rate ranges and what's included",
    "Who the experience is best for (couples, families, groups)",
    "Walking distances to key landmarks",
    "Recent editorial coverage",
    "Event and celebration offerings",
    "Accessibility and policy information",
  ],
  askExamples: [
    "Would you recommend {name} for a romantic weekend?",
    "Is {name} good for families?",
    "What is {name} known for?",
    "Should I stay at {name} or {competitor}?",
  ],
  marketNames: {
    lodging: ["The Solano Condado", "Hotel Arenisca", "Villa Coralina Resort", "La Ventana Suites", "Brisa Ocean House", "Hotel Almendro", "Palma Real Inn", "Costa Azul Residences"],
    dining: ["Fogón de Mar", "Cocina Almendro", "La Terraza Azul", "Pilón Kitchen", "Barra Marea", "El Patio de Lola", "Sal y Humo", "Mesa Isleña"],
    experience: ["Isla Luminosa Tours", "Yunque Trail Co.", "Bahía Kayak Adventures", "Sabor Food Walks", "Coral Snorkel PR", "Ruta Isleña Experiences"],
  },
};
