import type { IndustryConfig } from "../types";

const firmTemplates = [
  { topic: "best-provider", intent: "high-intent", text: "Best {plural} in {city}" },
  { topic: "best-provider", intent: "comparison", text: "What are the best {plural} in {city} for {focus}?" },
  { topic: "specialized", intent: "high-intent", text: "Best {plural} in {region} for {focus}" },
  { topic: "specialized", intent: "problem", text: "Who should I hire for {focus} in {region}?" },
  { topic: "local", intent: "local", text: "{plural} near {city} with local expertise" },
  { topic: "local", intent: "local", text: "Top-rated {noun} in {city}" },
  { topic: "pricing", intent: "comparison", text: "Affordable {noun} in {city} with good reviews" },
  { topic: "pricing", intent: "problem", text: "How much does a {noun} cost in {region}?" },
  { topic: "industry", intent: "discovery", text: "{plural} in {region} that specialize in {focus}" },
  { topic: "trust", intent: "comparison", text: "Most trusted {plural} in {region}" },
  { topic: "trust", intent: "discovery", text: "Which {noun} in {city} has the best reputation?" },
  { topic: "client-type", intent: "transactional", text: "Hire a {noun} in {city} for a small business" },
  { topic: "client-type", intent: "problem", text: "I'm relocating my company to {region} — which {noun} should I talk to?" },
  { topic: "specialized", intent: "transactional", text: "Book a consultation with a {noun} for {focus} in {city}" },
] as const;

export const professionalServices: IndustryConfig = {
  id: "professional-services",
  label: "Professional Services",
  emoji: "⚖️",
  tagline: "Know which firms AI trusts when customers ask for expertise.",
  audience: "clients",
  categories: [
    {
      id: "law",
      label: "Law firm",
      noun: "law firm",
      plural: "law firms",
      services: ["Corporate & business law", "Real estate law", "Litigation", "Immigration"],
      templateGroup: "firm",
      focuses: ["a business dispute", "startups", "a real estate dispute", "Act 60 compliance", "employment issues", "contract review"],
    },
    {
      id: "accounting",
      label: "Accounting / CPA firm",
      noun: "accounting firm",
      plural: "accounting firms",
      services: ["Tax preparation & planning", "Bookkeeping", "Audit & assurance", "Act 60 tax compliance"],
      templateGroup: "firm",
      focuses: ["small businesses", "startups", "Act 60 tax planning", "payroll", "audits", "nonprofits"],
    },
    {
      id: "architecture",
      label: "Architecture firm",
      noun: "architecture firm",
      plural: "architects",
      services: ["Residential architecture", "Commercial architecture", "Hurricane-resilient design", "Interior architecture"],
      templateGroup: "firm",
      focuses: ["a beach house", "hurricane-resilient homes", "commercial buildings", "historic renovations", "hotels", "sustainable design"],
    },
    {
      id: "consulting",
      label: "Consulting firm",
      noun: "consulting firm",
      plural: "consulting firms",
      services: ["Strategy consulting", "Operations consulting", "Government grants advisory", "Market entry"],
      templateGroup: "firm",
      focuses: ["market entry", "federal grants", "operations", "growth strategy", "manufacturing", "healthcare"],
    },
    {
      id: "contractor",
      label: "Contractor",
      noun: "general contractor",
      plural: "contractors",
      services: ["Home renovations", "Commercial build-outs", "Roofing & waterproofing", "Solar installation"],
      templateGroup: "firm",
      focuses: ["a kitchen renovation", "roof waterproofing", "solar panels", "a commercial build-out", "hurricane repairs", "concrete homes"],
    },
    {
      id: "marketing",
      label: "Marketing agency",
      noun: "marketing agency",
      plural: "marketing agencies",
      services: ["Brand strategy", "Digital marketing", "Social media", "Bilingual campaigns"],
      templateGroup: "firm",
      focuses: ["bilingual campaigns", "restaurants", "real estate marketing", "B2B companies", "tourism brands", "social media"],
    },
    {
      id: "financial-advisor",
      label: "Financial advisor",
      noun: "financial advisor",
      plural: "financial advisors",
      services: ["Wealth management", "Retirement planning", "Act 60 relocation planning", "Investment management"],
      templateGroup: "firm",
      focuses: ["retirement planning", "Act 60 relocation", "wealth management", "business owners", "estate planning", "young professionals"],
    },
  ],
  topics: [
    {
      id: "best-provider",
      label: "Best provider",
      phrase: "“best firm” questions",
      keywords: ["best", "top", "leading", "recommend", "who should i hire", "good"],
      opportunity: {
        title: "Win more “best {service} in {city}” recommendations",
        why: "These are the highest-volume questions clients ask, and AI lists competitors ahead of you because they have more third-party validation.",
        action: "Earn placement in local “best of” lists, bar/society directories and business press, and make sure each one describes your core service consistently.",
      },
      winSignals: ["Listed in “best of” roundups", "Many third-party references", "Consistent descriptions across directories"],
    },
    {
      id: "local",
      label: "Local expertise",
      phrase: "local expertise",
      keywords: ["near", "local", "in san juan", "nearby", "close", "office"],
      opportunity: {
        title: "Strengthen your local signals in {city}",
        why: "AI isn't confident about where you operate. Competitors with consistent address, map and directory data are recommended for local questions.",
        action: "Align your name, address and service area across your website, Google Business Profile, Yelp and local chambers; add a dedicated {city} office page.",
      },
      winSignals: ["Stronger local signals", "Consistent directory listings", "Dedicated location pages"],
    },
    {
      id: "specialized",
      label: "Specialized services",
      phrase: "specialized services",
      keywords: ["specialize", "specialist", "expert", "dispute", "tax", "audit", "planning", "compliance", "act 60"],
      opportunity: {
        title: "Make your specialties unmistakable",
        why: "AI associates you strongly with your core service, but rarely recommends you for adjacent specialties you actually offer.",
        action: "Create a dedicated, in-depth page for each specialty with process, typical clients, outcomes and FAQs.",
      },
      winSignals: ["More specific service pages", "Specialty-level FAQs", "Published case outcomes"],
    },
    {
      id: "pricing",
      label: "Pricing & value",
      phrase: "pricing and value",
      keywords: ["cost", "price", "affordable", "cheap", "fee", "how much", "budget", "value"],
      opportunity: {
        title: "Give AI something to say about your pricing",
        why: "When clients ask about cost, AI recommends firms that publish pricing guidance. You publish none, so you're left out.",
        action: "Publish transparent pricing ranges or engagement models (fixed fee, retainer, hourly) for your main services.",
      },
      winSignals: ["Published pricing guidance", "Clear engagement models", "Value-focused reviews"],
    },
    {
      id: "industry",
      label: "Industry expertise",
      phrase: "industry expertise",
      keywords: ["industry", "sector", "startups", "healthcare", "manufacturing", "nonprofit", "restaurants", "tech"],
      opportunity: {
        title: "Prove your industry expertise",
        why: "AI recommends firms it can tie to specific industries. It doesn't know which sectors you serve best.",
        action: "Add industry pages (e.g. startups, healthcare, hospitality) with client examples and sector-specific insights.",
      },
      winSignals: ["Industry-specific case studies", "Thought leadership by sector", "Named industry clients"],
    },
    {
      id: "trust",
      label: "Trust & reputation",
      phrase: "trust and reputation",
      keywords: ["trust", "reputation", "reviews", "reliable", "rated", "credible", "experienced"],
      opportunity: {
        title: "Build the reputation signals AI relies on",
        why: "AI weighs reviews, awards, years in practice and press when deciding which firm to trust. Competitors simply have more evidence.",
        action: "Ask satisfied clients for reviews, publish credentials and awards, and pursue two to three earned media mentions per quarter.",
      },
      winSignals: ["More authoritative references", "Higher review volume", "Awards and professional recognition"],
    },
    {
      id: "client-type",
      label: "Client fit",
      phrase: "client fit",
      keywords: ["small business", "startup", "individual", "company", "family", "relocating", "founder"],
      opportunity: {
        title: "Tell AI exactly who you're best for",
        why: "AI can't match you to client types because your website speaks to everyone. Competitors that name their ideal clients get recommended.",
        action: "Add “Who we work with” sections naming client types (small businesses, startups, relocating founders) with a short story for each.",
      },
      winSignals: ["Clear ideal-client positioning", "Client stories by segment", "Segment-specific landing pages"],
    },
  ],
  templates: { firm: [...firmTemplates] },
  strengths: [
    "Strong local presence in {city}",
    "Clear service offering",
    "Positive third-party mentions",
    "Relevant website content",
    "Established professional credentials",
    "Bilingual service",
  ],
  missingInfo: [
    "Specialty pages for each service you offer",
    "Published pricing or engagement models",
    "Client case studies with outcomes",
    "Professional awards and recognitions",
    "Industries and client types you serve",
    "Bios for partners with credentials",
    "Recent press or speaking engagements",
  ],
  askExamples: [
    "Would you recommend {name} for a startup?",
    "Is {name} a good {noun} for small businesses in {city}?",
    "What is {name} known for?",
    "Should I hire {name} or {competitor}?",
  ],
  marketNames: {
    firm: ["Montalvo Advisory Group", "Cruz Pagán & Associates", "Bayview Partners", "Ocean Park Advisors", "Norte Professional Group", "Ceiba Consulting", "Almendro & Vega", "Torre Plaza Advisors"],
  },
};
