import type { IndustryConfig } from "./types";

export const professionalServices: IndustryConfig = {
  id: "professional-services",
  label: "Professional Services",
  emoji: "⚖️",
  tagline: "Know which firms AI trusts when customers ask for expertise.",
  audience: "clients",
  subcategories: [
    {
      id: "accounting",
      label: "Accounting / CPA firm",
      group: "firm",
      noun: "accounting firm",
      plural: "accounting firms",
      services: ["Tax planning", "Bookkeeping", "Audit & assurance", "CFO advisory"],
      specialties: ["Growing businesses", "Act 60 tax compliance", "Construction companies", "Startups"],
      target_customer: "Small and growing businesses",
      base: { tax: 0.55, "small-business": 0.5, audit: 0.4, advisory: 0.35 },
      vars: {
        service: [
          { value: "tax planning", attrs: ["tax"] },
          { value: "bookkeeping", attrs: ["small-business"] },
          { value: "audit services", attrs: ["audit"] },
          { value: "fractional CFO services", attrs: ["advisory"] },
          { value: "Act 60 tax compliance", attrs: ["act-60", "tax"], persona: "Act 60 decree holders" },
        ],
        provider_type: [
          { value: "CPA firms", attrs: ["tax"] },
          { value: "accounting firms", attrs: [] },
          { value: "business advisors", attrs: ["advisory"] },
        ],
        problem: [
          { value: "a Hacienda tax audit", attrs: ["tax", "audit"], persona: "Business owners" },
          { value: "cleaning up two years of messy books", attrs: ["small-business"], persona: "Small business owners" },
          { value: "preparing financials for a bank loan", attrs: ["audit", "advisory"], persona: "Growing companies" },
          { value: "Act 60 decree compliance", attrs: ["act-60"], persona: "Act 60 decree holders" },
          { value: "payroll and IVU compliance", attrs: ["small-business", "tax"], persona: "Small business owners" },
          { value: "raising a seed round", attrs: ["startups", "advisory"], persona: "Founders" },
        ],
      },
    },
    {
      id: "law",
      label: "Law firm",
      group: "firm",
      noun: "law firm",
      plural: "law firms",
      services: ["Corporate law", "Real estate law", "Litigation", "Immigration"],
      specialties: ["Startups", "Business disputes", "Act 60", "Contracts"],
      target_customer: "Businesses and individuals",
      base: { "specialized-expertise": 0.5, reputation: 0.45 },
      vars: {
        service: [
          { value: "corporate law", attrs: ["specialized-expertise"] },
          { value: "real estate law", attrs: ["specialized-expertise"] },
          { value: "business litigation", attrs: ["specialized-expertise"] },
          { value: "Act 60 legal compliance", attrs: ["act-60"] },
        ],
        provider_type: [
          { value: "law firms", attrs: [] },
          { value: "business attorneys", attrs: ["small-business"] },
        ],
        problem: [
          { value: "a business dispute", attrs: ["specialized-expertise"], persona: "Business owners" },
          { value: "a real estate dispute", attrs: ["specialized-expertise"], persona: "Property owners" },
          { value: "incorporating a startup", attrs: ["startups"], persona: "Founders" },
          { value: "reviewing a commercial lease", attrs: ["small-business"], persona: "Business owners" },
        ],
      },
    },
    {
      id: "consulting",
      label: "Consulting firm",
      group: "firm",
      noun: "consulting firm",
      plural: "consulting firms",
      services: ["Strategy consulting", "Operations consulting", "Federal grants advisory"],
      specialties: ["Market entry", "Federal funds", "Manufacturing"],
      target_customer: "Mid-size companies and public agencies",
      base: { advisory: 0.6, "industry-expertise": 0.45 },
    },
    {
      id: "architecture",
      label: "Architecture firm",
      group: "firm",
      noun: "architecture firm",
      plural: "architecture firms",
      services: ["Residential architecture", "Commercial architecture", "Hurricane-resilient design"],
      specialties: ["Beach houses", "Historic renovations", "Hotels"],
      target_customer: "Homeowners and developers",
      base: { "specialized-expertise": 0.55 },
    },
    {
      id: "contractor",
      label: "Contractor",
      group: "firm",
      noun: "general contractor",
      plural: "contractors",
      services: ["Home renovations", "Commercial build-outs", "Roofing", "Solar installation"],
      specialties: ["Hurricane repairs", "Kitchens", "Concrete homes"],
      target_customer: "Homeowners and businesses",
      base: { responsiveness: 0.5, "local-presence": 0.55 },
    },
    {
      id: "marketing",
      label: "Marketing agency",
      group: "firm",
      noun: "marketing agency",
      plural: "marketing agencies",
      services: ["Brand strategy", "Digital marketing", "Social media"],
      specialties: ["Bilingual campaigns", "Tourism brands", "B2B"],
      target_customer: "Local and regional brands",
      base: { bilingual: 0.55, "industry-expertise": 0.45 },
    },
    {
      id: "financial-advisor",
      label: "Financial advisor",
      group: "firm",
      noun: "financial advisor",
      plural: "financial advisors",
      services: ["Wealth management", "Retirement planning", "Act 60 planning"],
      specialties: ["Business owners", "Relocating executives"],
      target_customer: "Individuals and families",
      base: { advisory: 0.55, "act-60": 0.4 },
    },
  ],
  categories: [
    { id: "best-provider", label: "Best provider" },
    { id: "specialized", label: "Specialized services" },
    { id: "client-fit", label: "Client fit" },
    { id: "industry", label: "Industry expertise" },
    { id: "local", label: "Local" },
    { id: "urgent", label: "Urgent problems" },
  ],
  attrCategory: { startups: "client-fit", "small-business": "client-fit", construction: "industry", "act-60": "specialized", "industry-expertise": "industry", tax: "specialized", audit: "specialized", "local-presence": "local", responsiveness: "urgent" },
  attributes: [
    { id: "tax", label: "Tax", rationale: "Tax planning depth", prose: "strong tax planning work", diagnosis: "tax-planning expertise", action: "Publish tax-planning guides for Puerto Rico businesses (IVU, estimated payments, incentives) under named partners.", keywords: ["tax", "taxes", "hacienda", "irs", "ivu"] },
    { id: "audit", label: "Audit", rationale: "Audit and assurance credentials", prose: "established audit and assurance practice", diagnosis: "audit credibility", action: "Describe your audit practice: industries audited, licenses and engagement process.", keywords: ["audit", "assurance", "financial statements"] },
    { id: "advisory", label: "Advisory", rationale: "Strategic advisory for growing companies", prose: "hands-on advisory for growing companies", diagnosis: "growth-advisory positioning", action: "Create an advisory page with outcomes for growing clients: forecasting, financing, CFO support.", keywords: ["advisory", "advisor", "cfo", "strategy", "growth", "growing"] },
    { id: "startups", label: "Startups", rationale: "Startup experience", prose: "experience with startups and founders", diagnosis: "startup expertise", action: "Add a startups page (incorporation, cap tables, investor-ready financials) with founder stories.", keywords: ["startup", "startups", "founder", "seed", "venture"] },
    { id: "small-business", label: "Small business", rationale: "Small-business focus", prose: "a practical focus on small businesses", diagnosis: "small-business positioning", action: "Name small businesses as a core client type, with packages and pricing guidance for them.", keywords: ["small business", "small businesses", "bookkeeping", "payroll", "owner"] },
    { id: "construction", label: "Construction", rationale: "Construction-industry expertise", prose: "deep construction-industry experience", diagnosis: "construction-industry expertise", action: "Publish a construction-industry page: job costing, bonding, percentage-of-completion accounting and client examples.", keywords: ["construction", "contractor", "builders"] },
    { id: "act-60", label: "Act 60", rationale: "Act 60 specialization", prose: "specialized Act 60 compliance knowledge", diagnosis: "Act 60 specialization", action: "Create an Act 60 hub: annual reports, residency tests and donation requirements, with a named practice lead.", keywords: ["act 60", "act60", "decree", "relocat"] },
    { id: "industry-expertise", label: "Industry expertise", rationale: "Sector-specific expertise", prose: "sector-specific expertise", diagnosis: "industry specialization", action: "Add industry pages (healthcare, hospitality, manufacturing) with sector insights and client examples.", keywords: ["industry", "healthcare", "manufacturing", "restaurants", "sector"] },
    { id: "local-presence", label: "Local presence", rationale: "Strong local presence", prose: "a well-established local presence", diagnosis: "local presence", action: "Align your name, address and service area across your website, Google Business Profile and local directories.", keywords: ["near", "local", "san juan", "nearby", "office"] },
    { id: "bilingual", label: "Bilingual", rationale: "Bilingual service", prose: "fully bilingual service", diagnosis: "bilingual service", action: "Make bilingual service explicit on every service page and publish key content in both languages.", keywords: ["bilingual", "english", "spanish"] },
    { id: "pricing", label: "Pricing clarity", rationale: "Transparent pricing", prose: "transparent, published pricing", diagnosis: "pricing transparency", action: "Publish engagement models and starting prices for your main services.", keywords: ["cost", "price", "affordable", "fee", "how much", "cheap"] },
    { id: "responsiveness", label: "Responsiveness", rationale: "Fast, responsive service", prose: "fast, responsive client service", diagnosis: "responsiveness", action: "State response times and onboarding speed, and ask clients to mention responsiveness in reviews.", keywords: ["fast", "quick", "urgent", "this week", "responsive"] },
    { id: "specialized-expertise", label: "Specialized expertise", rationale: "Specialized expertise", prose: "recognized specialized expertise", diagnosis: "specialist positioning", action: "Create an in-depth page for each specialty with process, typical clients and outcomes.", keywords: ["specialist", "specialized", "expert", "dispute", "litigation"] },
  ],
  vars: {
    service: [
      { value: "business consulting", attrs: ["advisory"] },
      { value: "professional services", attrs: [] },
    ],
    provider_type: [{ value: "firms", attrs: [] }],
    client_type: [
      { value: "startups", attrs: ["startups"], persona: "Founders" },
      { value: "small businesses", attrs: ["small-business"], persona: "Small business owners" },
      { value: "growing construction companies", attrs: ["construction", "advisory"], persona: "Construction owners" },
      { value: "Act 60 decree holders", attrs: ["act-60"], persona: "Act 60 decree holders" },
      { value: "family-owned businesses", attrs: ["small-business"], persona: "Family business owners" },
    ],
    problem: [
      { value: "a complex business problem", attrs: ["specialized-expertise"], persona: "Business owners" },
      { value: "getting a growing company organized", attrs: ["advisory"], persona: "Growing companies" },
    ],
    industry_vertical: [
      { value: "construction", attrs: ["construction"], persona: "Construction owners" },
      { value: "healthcare", attrs: ["industry-expertise"], persona: "Healthcare operators" },
      { value: "restaurants", attrs: ["industry-expertise", "small-business"], persona: "Restaurant owners" },
      { value: "tech startups", attrs: ["startups"], persona: "Founders" },
      { value: "manufacturing", attrs: ["industry-expertise"], persona: "Manufacturers" },
    ],
  },
  templates: [
    { id: "ps-best-service-client", text: "Best {service} in {location} for {client_type}", intent: "best-of", category: "client-fit", funnel: "consideration", persona: "Business owners", groups: ["firm"] },
    { id: "ps-who-hire-problem", text: "Who should I hire for {problem} in {location}?", intent: "problem", category: "urgent", funnel: "consideration", persona: "Business owners", groups: ["firm"] },
    { id: "ps-best-provider-industry", text: "Best {provider_type} for {industry_vertical} companies in {location}", intent: "best-of", category: "industry", funnel: "consideration", persona: "Business owners", groups: ["firm"] },
    { id: "ps-top-firms-service", text: "Top firms for {service} in {location}", intent: "best-of", category: "best-provider", funnel: "consideration", persona: "Business owners", groups: ["firm"], attrs: [] },
    { id: "ps-compare", text: "Compare {provider_type} in {location} for {client_type}", intent: "comparison", category: "client-fit", funnel: "consideration", persona: "Business owners", groups: ["firm"] },
    { id: "ps-local", text: "{provider_type} near {location} with bilingual service", intent: "local", category: "local", funnel: "consideration", persona: "Business owners", groups: ["firm"], attrs: ["local-presence", "bilingual"], scope: "local" },
    { id: "ps-high-growing", text: "Which {provider_type} in {location} would you recommend for a growing {industry_vertical} company?", intent: "high-intent", category: "industry", funnel: "decision", persona: "Business owners", groups: ["firm"], attrs: ["advisory"] },
    { id: "ps-urgent", text: "I need help with {problem} this month. Which firm in {location} can start quickly?", intent: "high-intent", category: "urgent", funnel: "decision", persona: "Business owners", groups: ["firm"], attrs: ["responsiveness"], scope: "local" },
    { id: "ps-book", text: "Book a consultation for {service} in {location}", intent: "transactional", category: "specialized", funnel: "decision", persona: "Business owners", groups: ["firm"], scope: "local" },
    { id: "ps-discovery-cost", text: "How much does {service} cost in {location}, and who offers it?", intent: "discovery", category: "best-provider", funnel: "awareness", persona: "Business owners", groups: ["firm"], attrs: ["pricing"] },
    { id: "ps-best-cpa-construction", text: "Best {provider_type} in {location} for {client_type}?", intent: "high-intent", category: "client-fit", funnel: "decision", persona: "Business owners", groups: ["firm"] },
  ],
  marketNames: {
    firm: ["Torre Plaza Advisors", "Norte Professional Group", "Almendro & Vega", "Ceiba Partners", "Ocean Park Advisors"],
  },
  missingInfo: [
    "Specialty pages for each service you offer",
    "Published pricing or engagement models",
    "Client case studies with outcomes",
    "Professional awards and recognitions",
    "Industries and client types you serve",
    "Partner bios with credentials",
  ],
  askExamples: [
    "Would you recommend {name} for a growing construction company?",
    "Is {name} a good fit for startups?",
    "What is {name} known for?",
    "Should I hire {name} or {competitor}?",
  ],
};
