import type { IndustryConfig } from "../types";

export const realEstate: IndustryConfig = {
  id: "real-estate",
  label: "Real Estate",
  emoji: "🏢",
  tagline: "Know which properties, neighborhoods and services AI recommends.",
  audience: "buyers, renters and investors",
  categories: [
    {
      id: "developer",
      label: "Property developer",
      noun: "developer",
      plural: "real estate developers",
      services: ["Luxury residential condos", "Mixed-use development", "Beachfront residences", "Vacation-rental ready units"],
      templateGroup: "developer",
      focuses: ["luxury condos", "beachfront residences", "pre-construction units", "investment condos", "gated communities", "mixed-use projects"],
    },
    {
      id: "brokerage",
      label: "Real estate brokerage",
      noun: "real estate brokerage",
      plural: "real estate brokerages",
      services: ["Residential sales", "Luxury listings", "Relocation services", "Investment property sales"],
      templateGroup: "agent",
      focuses: ["luxury homes", "relocating to Puerto Rico", "first-time buyers", "investment properties", "beachfront homes", "Act 60 relocations"],
    },
    {
      id: "realtor",
      label: "Realtor / agent",
      noun: "realtor",
      plural: "realtors",
      services: ["Buyer representation", "Luxury listings", "Relocation", "Condo sales"],
      templateGroup: "agent",
      focuses: ["luxury homes", "relocating to Puerto Rico", "first-time buyers", "condos", "beachfront homes", "Act 60 relocations"],
    },
    {
      id: "property-manager",
      label: "Property manager",
      noun: "property management company",
      plural: "property management companies",
      services: ["Short-term rental management", "Long-term rental management", "HOA management", "Commercial property management"],
      templateGroup: "manager",
      focuses: ["Airbnb rentals", "long-term rentals", "condo associations", "vacation homes", "commercial buildings", "absentee owners"],
    },
    {
      id: "mortgage",
      label: "Mortgage / financing",
      noun: "mortgage lender",
      plural: "mortgage lenders",
      services: ["Residential mortgages", "Investment property loans", "Construction financing", "Foreign national loans"],
      templateGroup: "mortgage",
      focuses: ["first-time buyers", "investment properties", "self-employed buyers", "relocating buyers", "construction loans", "refinancing"],
    },
  ],
  topics: [
    {
      id: "invest",
      label: "Where to invest",
      phrase: "real estate investment",
      keywords: ["invest", "investment", "roi", "yield", "return", "portfolio", "appreciation"],
      opportunity: {
        title: "Become more authoritative for real estate investment in {city}",
        why: "AI frequently recommends competitors when users ask where and how to invest. It has little evidence that you understand yields, neighborhoods and investor needs.",
        action: "Publish a detailed investment guide covering neighborhoods, rental yields, property types, Act 60 considerations and market risks — with your own projects as worked examples.",
      },
      winSignals: ["Published investment guides with real yield data", "Citations in regional market reports", "Clear investor-focused service pages"],
    },
    {
      id: "neighborhoods",
      label: "Best neighborhoods",
      phrase: "neighborhood recommendations",
      keywords: ["neighborhood", "area", "where to live", "where should i buy", "best place", "location", "zone"],
      opportunity: {
        title: "Own the neighborhood conversation around {city}",
        why: "When people ask AI which areas to live or buy in, it cites businesses with neighborhood-level content. Yours is rarely referenced.",
        action: "Create neighborhood pages for each area you serve: lifestyle, price ranges, schools, walkability and what's being built.",
      },
      winSignals: ["Neighborhood-level guides", "Strong local signals across directories", "Mentions in local press"],
    },
    {
      id: "developers",
      label: "Developers",
      phrase: "trusted developers",
      keywords: ["developer", "builder", "construction", "pre-construction", "new development", "project"],
      opportunity: {
        title: "Strengthen your track record as a developer",
        why: "AI recommends developers it can verify through completed projects, delivery history and third-party coverage. Your track record is hard for it to find.",
        action: "Add a portfolio page with every completed project: delivery dates, unit counts, architects, awards and press coverage.",
      },
      winSignals: ["Documented portfolio of delivered projects", "Press coverage of launches", "Named architects and partners"],
    },
    {
      id: "agents",
      label: "Realtors & brokers",
      phrase: "agent recommendations",
      keywords: ["realtor", "agent", "broker", "brokerage", "sell my", "buy a home", "listing"],
      opportunity: {
        title: "Get recommended when buyers ask for an agent",
        why: "AI leans on reviews, transaction history and specialization when recommending agents. It sees you as generalist.",
        action: "Publish client stories by buyer type (relocation, investor, first-time) and keep review profiles active on major platforms.",
      },
      winSignals: ["High review volume on major platforms", "Clear buyer specialization", "Transaction history visible online"],
    },
    {
      id: "property-types",
      label: "Property types",
      phrase: "specific property types",
      keywords: ["condo", "apartment", "villa", "house", "land", "penthouse", "townhouse"],
      opportunity: {
        title: "Clarify which property types you specialize in",
        why: "AI understands your company but does not clearly associate it with specific property types, so it defaults to competitors with clearer positioning.",
        action: "Restructure your website around property types — dedicated pages for condos, villas and penthouses with specs, pricing ranges and availability.",
      },
      winSignals: ["Dedicated pages per property type", "Structured listing data", "Specific pricing ranges"],
    },
    {
      id: "rentals",
      label: "Rental opportunities",
      phrase: "rental income",
      keywords: ["rent", "rental", "airbnb", "short-term", "long-term", "tenant", "vacation rental"],
      opportunity: {
        title: "Show up for rental-income questions",
        why: "Investors ask AI which properties generate reliable rental income. You aren't associated with rental performance.",
        action: "Publish rental performance data for your properties (occupancy, nightly rates, management options) and a short-term rental regulations explainer.",
      },
      winSignals: ["Published occupancy and rate data", "Rental management partnerships", "Clear STR regulation content"],
    },
    {
      id: "luxury",
      label: "Luxury properties",
      phrase: "luxury real estate",
      keywords: ["luxury", "high-end", "premium", "exclusive", "penthouse", "upscale"],
      opportunity: {
        title: "Clarify your luxury offering",
        why: "AI understands your company but does not clearly associate it with luxury residential. Competitors with richer luxury signals are recommended instead.",
        action: "Strengthen your website's positioning around luxury: amenities, finishes, architects, price points and coverage in lifestyle publications.",
      },
      winSignals: ["Coverage in lifestyle and luxury publications", "Detailed amenity and finish specs", "Premium price positioning"],
    },
    {
      id: "commercial",
      label: "Commercial real estate",
      phrase: "commercial real estate",
      keywords: ["commercial", "office", "retail", "industrial", "warehouse", "mixed-use"],
      opportunity: {
        title: "Enter the commercial real estate conversation in {city}",
        why: "AI almost never connects your brand with commercial or mixed-use real estate, even though it's adjacent to what you do.",
        action: "Create a commercial real estate page explaining your mixed-use experience, tenant mix and investment structure.",
      },
      winSignals: ["Commercial project case studies", "Tenant and leasing information", "Investor relations content"],
    },
    {
      id: "financing",
      label: "Financing",
      phrase: "financing guidance",
      keywords: ["mortgage", "loan", "financing", "finance", "down payment", "lender", "credit"],
      opportunity: {
        title: "Answer the financing questions buyers ask first",
        why: "Buyers ask AI how financing works before they ask who to buy from. Businesses that explain financing get recommended earlier in the journey.",
        action: "Publish a buyer financing guide: local lenders, foreign-buyer options, down payments and pre-construction payment schedules.",
      },
      winSignals: ["Clear financing guides", "Named lending partners", "Calculators and payment schedules"],
    },
    {
      id: "market",
      label: "Market trends",
      phrase: "market insight",
      keywords: ["market", "trend", "prices", "forecast", "2026", "2027", "outlook", "bubble"],
      opportunity: {
        title: "Become a source AI cites on market trends",
        why: "AI quotes businesses that publish original market data. Right now it cites brokerages and media instead of you.",
        action: "Publish a quarterly market report with original data on prices, absorption and demand in your area.",
      },
      winSignals: ["Original quarterly market reports", "Quotes in news coverage", "Data-rich blog content"],
    },
  ],
  templates: {
    developer: [
      { topic: "invest", intent: "discovery", text: "Best areas to invest in {region} real estate" },
      { topic: "invest", intent: "high-intent", text: "Where should I buy an investment property in {city}?" },
      { topic: "developers", intent: "comparison", text: "Best developers for {focus} in {region}" },
      { topic: "developers", intent: "comparison", text: "Most reputable real estate developers in {city}" },
      { topic: "luxury", intent: "discovery", text: "Best new luxury condo projects in {city}" },
      { topic: "luxury", intent: "high-intent", text: "Who builds the highest quality luxury residences in {region}?" },
      { topic: "neighborhoods", intent: "local", text: "Best neighborhoods to buy a condo near {city}" },
      { topic: "property-types", intent: "transactional", text: "Buy {focus} in {city}" },
      { topic: "rentals", intent: "problem", text: "Which properties in {city} generate the best rental income?" },
      { topic: "rentals", intent: "high-intent", text: "Best {focus} for short-term rental income in {region}" },
      { topic: "commercial", intent: "discovery", text: "Commercial real estate opportunities in {city}" },
      { topic: "financing", intent: "problem", text: "How do I finance a pre-construction condo in {city}?" },
      { topic: "financing", intent: "comparison", text: "Which developers in {region} offer flexible payment plans for {focus}?" },
      { topic: "market", intent: "problem", text: "Is it a good time to buy real estate in {city}?" },
      { topic: "market", intent: "discovery", text: "What is the market outlook for {focus} in {region}?" },
      { topic: "invest", intent: "problem", text: "I'm moving to {region} under Act 60 — what property should I buy?" },
    ],
    agent: [
      { topic: "agents", intent: "high-intent", text: "Best {plural} in {city}" },
      { topic: "agents", intent: "comparison", text: "Best real estate agent in {city} for {focus}" },
      { topic: "agents", intent: "transactional", text: "Find a realtor to help me buy in {city}" },
      { topic: "luxury", intent: "discovery", text: "Top luxury real estate agents in {region}" },
      { topic: "neighborhoods", intent: "local", text: "Best neighborhoods to live in near {city}" },
      { topic: "neighborhoods", intent: "discovery", text: "Where should I live in {region} if I work remotely?" },
      { topic: "invest", intent: "high-intent", text: "Which agent should I use to buy an investment property in {region}?" },
      { topic: "property-types", intent: "transactional", text: "Homes for sale in {city} — who should I call?" },
      { topic: "rentals", intent: "problem", text: "Who can help me find a long-term rental in {city}?" },
      { topic: "market", intent: "problem", text: "How is the {city} housing market right now?" },
      { topic: "financing", intent: "problem", text: "How does buying a home in {region} work for a non-resident?" },
      { topic: "invest", intent: "discovery", text: "Best real estate brokerages in {region} for {focus}" },
    ],
    manager: [
      { topic: "rentals", intent: "high-intent", text: "Best {plural} in {city}" },
      { topic: "rentals", intent: "comparison", text: "Best property manager for {focus} in {region}" },
      { topic: "rentals", intent: "problem", text: "Who can manage my vacation rental in {city}?" },
      { topic: "invest", intent: "problem", text: "How do I maximize rental income from my property in {city}?" },
      { topic: "neighborhoods", intent: "local", text: "Best areas for short-term rentals near {city}" },
      { topic: "commercial", intent: "discovery", text: "Commercial property management companies in {region}" },
      { topic: "property-types", intent: "transactional", text: "Hire a company to manage {focus} in {city}" },
      { topic: "market", intent: "problem", text: "What are short-term rental regulations in {region}?" },
      { topic: "luxury", intent: "discovery", text: "Luxury vacation home management in {region}" },
      { topic: "agents", intent: "comparison", text: "Most trusted property management companies in {city}" },
    ],
    mortgage: [
      { topic: "financing", intent: "high-intent", text: "Best {plural} in {city}" },
      { topic: "financing", intent: "comparison", text: "Best mortgage lender in {region} for {focus}" },
      { topic: "financing", intent: "problem", text: "How do I get a mortgage in {region} as a non-resident?" },
      { topic: "financing", intent: "transactional", text: "Get pre-approved for a home loan in {city}" },
      { topic: "invest", intent: "high-intent", text: "Who finances investment properties in {region}?" },
      { topic: "luxury", intent: "discovery", text: "Jumbo loans for luxury homes in {region}" },
      { topic: "market", intent: "problem", text: "What are mortgage rates like in {region} right now?" },
      { topic: "developers", intent: "problem", text: "How does construction financing work in {region}?" },
      { topic: "neighborhoods", intent: "local", text: "Local mortgage brokers near {city}" },
      { topic: "agents", intent: "comparison", text: "Most trusted lenders in {city} according to buyers" },
    ],
  },
  strengths: [
    "Strong local presence in {city}",
    "Clear service offering",
    "Positive third-party mentions",
    "Relevant website content",
    "Consistent business information across directories",
    "Brand recognition in {region}",
  ],
  missingInfo: [
    "Completed project history with delivery dates",
    "Published price ranges per property type",
    "Investor-focused yield or rental data",
    "Third-party press coverage from the last 12 months",
    "Neighborhood-level content for the areas you serve",
    "Named architects, partners or lenders",
    "Client testimonials tied to specific buyer types",
  ],
  askExamples: [
    "Would you recommend {name} for a luxury real estate investment?",
    "Is {name} a good choice for buying a condo in {city}?",
    "What does {name} specialize in?",
    "Who is better for investment properties: {name} or {competitor}?",
  ],
  marketNames: {
    developer: ["Atlántico Realty Group", "Palmar Living", "Isla Capital Partners", "Bahía Development Co.", "Ceiba Properties", "Cumbre Residences", "Marbella Norte Group", "Puerta de Tierra Developers"],
    agent: ["Atlántico Realty Group", "Casa Isla Realty", "Ceiba Properties", "Norte Homes PR", "Brisa Realty Partners", "Sotavento Real Estate", "Lumen Property Advisors"],
    manager: ["Isla Stays Management", "Ceiba Property Services", "Coastline Rentals PR", "Norte Asset Management", "Brisa Hosting Co.", "Sotavento Property Care"],
    mortgage: ["Isla Home Lending", "Norte Mortgage Partners", "Ceiba Financial", "Coastal Capital Lending", "Puerto Bridge Loans", "Bahía Home Finance"],
  },
};
