import type { IndustryConfig } from "./types";

export const realEstate: IndustryConfig = {
  id: "real-estate",
  label: "Real Estate",
  emoji: "🏢",
  tagline: "Know which properties, neighborhoods and services AI recommends.",
  audience: "buyers and investors",
  subcategories: [
    {
      id: "developer",
      label: "Property developer",
      group: "developer",
      noun: "real estate developer",
      plural: "real estate developers",
      services: ["Residential development", "Luxury condos", "Investment properties", "Mixed-use development"],
      specialties: ["Waterfront projects", "Pre-construction sales", "Rental-ready units", "Act 60 buyers"],
      target_customer: "Investors and second-home buyers",
      base: { "track-record": 0.5, residential: 0.5, luxury: 0.4, investment: 0.4 },
    },
    {
      id: "brokerage",
      label: "Real estate brokerage",
      group: "agent",
      noun: "real estate brokerage",
      plural: "real estate brokerages",
      services: ["Residential sales", "Luxury listings", "Relocation services", "Investment property sales"],
      specialties: ["Relocation", "Luxury homes", "First-time buyers", "Investors"],
      target_customer: "Home buyers and relocating families",
      base: { neighborhood: 0.55, residential: 0.5, investment: 0.4 },
    },
    {
      id: "realtor",
      label: "Realtor / agent",
      group: "agent",
      noun: "realtor",
      plural: "realtors",
      services: ["Buyer representation", "Luxury listings", "Relocation", "Condo sales"],
      specialties: ["Relocation", "Luxury homes", "First-time buyers"],
      target_customer: "Home buyers",
      base: { neighborhood: 0.55, residential: 0.5 },
    },
    {
      id: "property-manager",
      label: "Property manager",
      group: "agent",
      noun: "property management company",
      plural: "property management companies",
      services: ["Short-term rental management", "Long-term rental management", "HOA management"],
      specialties: ["Airbnb rentals", "Absentee owners", "Condo associations"],
      target_customer: "Property owners and investors",
      base: { rental: 0.6, investment: 0.45 },
    },
    {
      id: "mortgage",
      label: "Mortgage / financing",
      group: "agent",
      noun: "mortgage lender",
      plural: "mortgage lenders",
      services: ["Residential mortgages", "Investment property loans", "Construction financing"],
      specialties: ["Non-resident buyers", "Self-employed buyers", "Investors"],
      target_customer: "Buyers and investors",
      base: { financing: 0.65, investment: 0.45 },
    },
  ],
  categories: [
    { id: "investment", label: "Investment" },
    { id: "neighborhoods", label: "Neighborhoods" },
    { id: "developers", label: "Developers" },
    { id: "rental", label: "Rental income" },
    { id: "luxury", label: "Luxury" },
    { id: "commercial", label: "Commercial" },
    { id: "financing", label: "Financing" },
  ],
  attrCategory: { luxury: "luxury", waterfront: "luxury", rental: "rental", commercial: "commercial", financing: "financing", neighborhood: "neighborhoods", investment: "investment" },
  attributes: [
    { id: "luxury", label: "Luxury", rationale: "Luxury residential positioning", prose: "high-end finishes and luxury amenities", diagnosis: "luxury residential positioning", action: "Strengthen your website and third-party positioning around luxury residences: finishes, amenities, architects and price points.", keywords: ["luxury", "high-end", "premium", "penthouse", "upscale"] },
    { id: "waterfront", label: "Waterfront", rationale: "Waterfront and beachfront projects", prose: "oceanfront and waterfront locations", diagnosis: "luxury waterfront positioning", action: "Publish dedicated pages for your waterfront projects (location, views, beach access) and pursue coverage of them in regional press.", keywords: ["waterfront", "beachfront", "ocean", "beach", "oceanfront"] },
    { id: "investment", label: "Investment", rationale: "Investor-focused guidance", prose: "clear guidance for investors", diagnosis: "real estate investment expertise", action: "Publish an investment guide covering neighborhoods, yields, property types and Act 60 considerations, using your own projects as worked examples.", keywords: ["invest", "investment", "investor", "roi", "yield", "appreciation", "act 60"] },
    { id: "rental", label: "Rental income", rationale: "Rental-income potential", prose: "strong rental-income potential", diagnosis: "rental-yield credibility", action: "Publish occupancy and rental-rate data for delivered units, and name your rental-management partners.", keywords: ["rent", "rental", "airbnb", "short-term", "long-term", "tenant"] },
    { id: "track-record", label: "Track record", rationale: "Proven delivery track record", prose: "a track record of delivered projects", diagnosis: "documented delivery track record", action: "Add a portfolio of completed projects with delivery dates, unit counts, architects and press coverage.", keywords: ["developer", "builder", "track record", "reputable", "delivered"] },
    { id: "pre-construction", label: "Pre-construction", rationale: "Pre-construction buying options", prose: "pre-construction buying options", diagnosis: "pre-construction expertise", action: "Explain your pre-construction process: deposit schedules, delivery timelines and buyer protections.", keywords: ["pre-construction", "new development", "off-plan", "new construction"] },
    { id: "commercial", label: "Commercial", rationale: "Commercial and mixed-use experience", prose: "experience with commercial and mixed-use projects", diagnosis: "commercial and mixed-use credibility", action: "Create a commercial real estate page explaining your mixed-use experience, tenant mix and investment structure.", keywords: ["commercial", "office", "retail", "mixed-use", "industrial"] },
    { id: "financing", label: "Financing", rationale: "Financing support", prose: "help with financing and payment plans", diagnosis: "financing guidance", action: "Publish a buyer financing guide: lending partners, non-resident options, down payments and payment plans.", keywords: ["mortgage", "loan", "financing", "finance", "down payment", "payment plan"] },
    { id: "neighborhood", label: "Neighborhood expertise", rationale: "Neighborhood expertise", prose: "deep knowledge of local neighborhoods", diagnosis: "neighborhood-level expertise", action: "Create neighborhood pages for each area you build in: lifestyle, price ranges, schools and what is coming next.", keywords: ["neighborhood", "area", "where to live", "location", "community"] },
    { id: "residential", label: "Residential", rationale: "Quality residential product", prose: "well-designed residential units", diagnosis: "residential product quality", action: "Show floor plans, specifications and resident testimonials for each residential project.", keywords: ["condo", "home", "apartment", "residential", "house"] },
    { id: "value", label: "Accessible pricing", rationale: "Accessible price points", prose: "more accessible price points", diagnosis: "entry-level pricing story", action: "Publish price ranges and an entry-level option so AI can recommend you for budget-conscious buyers.", keywords: ["budget", "affordable", "cheap", "first-time", "value"] },
  ],
  vars: {
    property_type: [
      { value: "luxury condo", attrs: ["luxury", "residential"], persona: "Luxury buyers" },
      { value: "beachfront condo", attrs: ["waterfront", "residential"], persona: "Second-home buyers" },
      { value: "pre-construction condo", attrs: ["pre-construction"], persona: "Investors" },
      { value: "multifamily", attrs: ["rental", "investment"], persona: "Investors" },
      { value: "vacation rental", attrs: ["rental"], persona: "Investors" },
      { value: "mixed-use", attrs: ["commercial"], persona: "Commercial investors" },
    ],
    investment_goal: [
      { value: "long-term rental income", attrs: ["rental", "investment"], persona: "Investors" },
      { value: "short-term rental income", attrs: ["rental"], persona: "Investors" },
      { value: "capital appreciation", attrs: ["investment"], persona: "Investors" },
      { value: "an Act 60 relocation", attrs: ["investment", "neighborhood"], persona: "Relocating investors" },
      { value: "a second home", attrs: ["luxury", "neighborhood"], persona: "Second-home buyers" },
    ],
    developer_type: [
      { value: "luxury condo developers", attrs: ["luxury", "track-record"] },
      { value: "waterfront developers", attrs: ["waterfront", "track-record"] },
      { value: "residential developers", attrs: ["track-record", "residential"] },
      { value: "mixed-use developers", attrs: ["commercial", "track-record"] },
    ],
    investment_strategy: [
      { value: "rental investors", attrs: ["rental"], persona: "Investors" },
      { value: "young families", attrs: ["neighborhood", "value"], persona: "Families" },
      { value: "remote workers", attrs: ["neighborhood"], persona: "Remote workers" },
      { value: "luxury buyers", attrs: ["luxury"], persona: "Luxury buyers" },
    ],
    budget: [
      { value: "under $400K", attrs: ["value"], persona: "First-time buyers" },
      { value: "around $750K", attrs: [] },
      { value: "over $1.5M", attrs: ["luxury"], persona: "Luxury buyers" },
    ],
    rental_objective: [
      { value: "Airbnb income", attrs: ["rental"] },
      { value: "long-term tenants", attrs: ["rental"] },
      { value: "corporate rentals", attrs: ["rental", "commercial"] },
    ],
    buyer_type: [
      { value: "a non-resident", attrs: ["financing"], persona: "Non-resident buyers" },
      { value: "a first-time buyer", attrs: ["financing", "value"], persona: "First-time buyers" },
      { value: "an investor", attrs: ["financing", "investment"], persona: "Investors" },
    ],
    commercial_type: [
      { value: "mixed-use", attrs: ["commercial"] },
      { value: "retail and office", attrs: ["commercial"] },
      { value: "hospitality", attrs: ["commercial", "luxury"] },
    ],
    lifestyle: [
      { value: "a beach lifestyle", attrs: ["waterfront"] },
      { value: "resort and golf living", attrs: ["luxury"] },
      { value: "walkable city living", attrs: ["neighborhood"] },
    ],
    market_objective: [
      { value: "rental investors", attrs: ["rental", "investment"], persona: "Investors" },
      { value: "luxury buyers", attrs: ["luxury"], persona: "Luxury buyers" },
      { value: "first-time buyers", attrs: ["value"], persona: "First-time buyers" },
    ],
  },
  templates: [
    { id: "re-best-type-invest", text: "Best {property_type} investments in {location}", intent: "best-of", category: "investment", funnel: "consideration", persona: "Investors", groups: ["developer", "agent"], attrs: ["investment"] },
    { id: "re-where-invest", text: "Where should I invest in {location} for {investment_goal}?", intent: "discovery", category: "investment", funnel: "awareness", persona: "Investors", groups: ["developer", "agent"], attrs: ["investment"] },
    { id: "re-best-devtype", text: "Best {developer_type} in {location}", intent: "best-of", category: "developers", funnel: "consideration", persona: "Buyers", groups: ["developer"] },
    { id: "re-neighborhoods", text: "Best neighborhoods in {location} for {investment_strategy}", intent: "local", category: "neighborhoods", funnel: "awareness", persona: "Buyers", groups: ["developer", "agent"], attrs: ["neighborhood"] },
    { id: "re-who-best-dev", text: "Who are the best real estate developers in {location}?", intent: "best-of", category: "developers", funnel: "consideration", persona: "Buyers", groups: ["developer"], attrs: ["track-record"] },
    { id: "re-compare-dev", text: "Compare the top {developer_type} in {location}", intent: "comparison", category: "developers", funnel: "consideration", persona: "Buyers", groups: ["developer"] },
    { id: "re-high-budget", text: "I want to buy a {property_type} in {location} {budget}. Who should I talk to?", intent: "high-intent", category: "luxury", funnel: "decision", persona: "Buyers", groups: ["developer", "agent"] },
    { id: "re-rental-dev", text: "Which developers in {location} build the best properties for {rental_objective}?", intent: "high-intent", category: "rental", funnel: "decision", persona: "Investors", groups: ["developer"], attrs: ["track-record"] },
    { id: "re-financing", text: "How do I finance a {property_type} in {location} as {buyer_type}?", intent: "problem", category: "financing", funnel: "consideration", persona: "Buyers", groups: ["developer", "agent"] },
    { id: "re-commercial", text: "Best developers for {commercial_type} projects in {location}", intent: "best-of", category: "commercial", funnel: "consideration", persona: "Commercial investors", groups: ["developer"], attrs: ["track-record"] },
    { id: "re-lifestyle", text: "Where should I buy a home in {location} for {lifestyle}?", intent: "discovery", category: "neighborhoods", funnel: "awareness", persona: "Second-home buyers", groups: ["developer", "agent"], attrs: ["residential"] },
    { id: "re-book", text: "Schedule a sales consultation for a {property_type} in {location}", intent: "transactional", category: "luxury", funnel: "decision", persona: "Buyers", groups: ["developer"], scope: "local" },
    { id: "re-market", text: "Is {location} a good market for {market_objective} right now?", intent: "problem", category: "investment", funnel: "awareness", persona: "Investors", groups: ["developer", "agent"], attrs: ["investment"] },
    { id: "re-best-agent", text: "Best real estate agents in {location} for {investment_strategy}", intent: "best-of", category: "neighborhoods", funnel: "consideration", persona: "Buyers", groups: ["agent"], attrs: ["neighborhood"] },
    { id: "re-agent-high", text: "Who should I hire to help me buy a {property_type} in {location}?", intent: "high-intent", category: "investment", funnel: "decision", persona: "Buyers", groups: ["agent"] },
    { id: "re-rental-manage", text: "Who can manage my {property_type} for {rental_objective} in {location}?", intent: "high-intent", category: "rental", funnel: "decision", persona: "Owners", groups: ["agent"], attrs: ["rental"] },
  ],
  marketNames: {
    developer: ["Ceiba Properties", "Marbella Norte Group", "Puerta de Tierra Developers", "Atlántico Realty Group"],
    agent: ["Casa Isla Realty", "Ceiba Properties", "Norte Homes PR", "Brisa Realty Partners", "Sotavento Real Estate"],
  },
  missingInfo: [
    "Completed project history with delivery dates",
    "Published price ranges per property type",
    "Rental yield or occupancy data",
    "Press coverage from the last 12 months",
    "Neighborhood-level content for the areas you build in",
    "Named architects, partners or lenders",
  ],
  askExamples: [
    "Would you recommend {name} for a luxury real estate investment?",
    "Is {name} a good choice for a beachfront condo?",
    "What does {name} specialize in?",
    "Who is better for rental investors: {name} or {competitor}?",
  ],
};
